version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test-and-coverage:
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
          pre-install: pip install --upgrade pip
      - python/test:
          args: "--cov=krcps"
          test-tool: pytest
      - run:
          name: Upload coverage to Codecov
          command: |
            codecov

workflows:
  test:
    jobs:
      - test-and-coverage