version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test-and-coverage:
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run:
          name: Update pip
          command: |
            pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run tests
          command: |
            pytest --cov=krcps --junitxml=test-results/junit.xml
      - run:
          name: Upload coverage results to Codecov
          command: |
            codecov
      - store_test_results:
          path: test-results

workflows:
  test:
    jobs:
      - test-and-coverage