name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  build:

    runs-on: ubuntu-latest
    stategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
    - name: Lint with black
      run: |
        python -m pip install black[jupyter]
        black --check .
    - name: Generate coverage report
      run: |
        python -m pip install pytest-cov
        pytest --cov=krcps --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
